### ISSUE TITLE
How to exit from loop after 5 seconds

### ISSUE THREAD

**Issue by garudaonekh** [php-mqtt/client-examples#6]
Hi,
Sorry, my background is C++ and I am trying to leave subscription loop if there's no data within 5 seconds.

I have look at this code but no idea how to set loop timeout.

https://github.com/php-mqtt/client-examples/blob/master/05_interuppting_the_loop/01_use_pcntl_signal_to_interrupt_the_loop.php

**Comment by Namoshek** [comment]
There are two ways to achieve this:

1. Use [`pcntl_alarm`](https://www.php.net/manual/de/function.pcntl-alarm.php) in combination with [`pcntl_signal`](https://www.php.net/manual/de/function.pcntl-signal.php) (requires the `pcntl` extension):
    ```php
    $client = new MqttClient($host, $port);
    
    pcntl_async_signals(true);
    pcntl_signal(SIGALRM, fn () => $client->interrupt());
    pcntl_alarm(5); // send SIGALRM after 5 seconds

    $client->connect(null, true);
    $client->loop(true);
    ```

2. Use a _loop event handler_ and the `$elapsedTime` parameter:
    ```php
    $client = new MqttClient($host, $port);

    $client->registerLoopEventHandler(function (MqttClient $client, float $elapsedTime) {
        if ($elapsedTime >= 5) {
            $client->interrupt();
        }
    });

    $client->connect(null, true);
    $client->loop(true);
    ```

**Comment by garudaonekh** [comment]
Thank you very much. It works
